;; The sequence of triangle numbers is generated by adding 
;; the natural numbers. So the 7^(th) triangle number would 
;; be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

;; What is the value of the first triangle number to have over five hundred divisors?

(load-file "eulerlib.clj")
(load-file "primes.clj")

(defn triangle-naiv [n] 
  "calculates the n-th triangle number in a bloody naiv way"
  (reduce + (range 1 (inc n))))

(defn triangle-gauss [n]
  "calculates the n-th triangle number with the little gauss"
  (quot (* n (inc n)) 2))

(defn triangles [] 
  "generate lazy sequence of triangle numbers"
  (map second 
       (rest (iterate 
               (fn [[a b]] [(inc a) (+ a b)]) 
               [1 0]))))

(defn solve012 [n] 
  (triangle-gauss (inc (count (take-while #(<= % n) 
                                          (map divisors-count (triangles)))))))

